version: "3"

services:
  database:
    image: postgres
    container_name: template-database
    restart: always
    environment:
      POSTGRES_USER: template-database
      POSTGRES_PASSWORD: database_Password1
      POSTGRES_DB: template

  template:
    build: ./
    container_name: template
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      API_PORT: 5000
      UI_PORT: 3000
      POSTGRES_CONNECTION_STRING: "Host=database;Port=5432;Database=template;Username=template-database;Password=database_Password1"
    depends_on:
      - database
